### ISSUE TITLE
Data from state

### ISSUE THREAD

**Issue by trotor** [praveenkumar-outlook/react-json-excel#17]
Hi, I am not able to make this work from typescript project (with json from server (axios.get). Your examples seem confusing also as if I do 
use Json To Csv version alone, it doesn't do anything and JsonToCsv in Render version doesn't load dynamic data  (this.state.x doesn't work, if I put the same content as static it works).

If I put both, it automaticlaly downloads three csv:s and one is correct. Can you provide better samples?

**Comment by praveenkumar-kalidass** [comment]
Hi @trotor ,
Thank you for your feedback.
I tried `useJsonToCsv`, i could not find the issue you have described. With respect to `JsonToCsv`, yes it does not load dynamic data and hence we need to make use of `useJsonToCsv`.

Can you please take a look at the link below for better samples,
https://github.com/praveenkumar-kalidass/react-json-csv/blob/master/dev/App.jsx

Please let me know, if the issue is still can not be resolved.
Thanks.

**Comment by trotor** [comment]
Hi, sorry for not responding earlier. I think I got it working or used alternative route. If you cannot reproduce it, close this. Thank you for your reply!
